apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::028702951943:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-539LLFMYEGIJ
      username: system:node:{{EC2PrivateDNSName}}
      - system:masters
      rolearn: arn:aws:iam::028702951943:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-24T22:38:08Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1556"
  uid: b45cd9d7-17d6-415e-82ea-a7b40f0cff47
