apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system: bootstrappers
      - system: nodes
      rolearn: arn:aws:iam::028702951943:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1ALPMHLW32U29
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::028702951943:role/UdacityFlaskDeployCBKubectlRole345
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-25T05:41:20Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "5007"
  uid: 73650bb2-b71d-4a78-a821-ab5134c3f9ac
