apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::028702951943:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-1CU5BUULA2JBG
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::028702951943:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  creationTimestamp: "2022-10-25T23:47:29Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1648"
  uid: 00f33860-4e46-42a0-bfb6-19b52b415f00
